/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as BillDemoStepperIndexRouteImport } from './routes/bill-demo/stepper/index'
import { Route as BillDemoSimpleIndexRouteImport } from './routes/bill-demo/simple/index'
import { Route as BillDemoDynamicIndexRouteImport } from './routes/bill-demo/dynamic/index'
import { Route as BillDemoAudienceIndexRouteImport } from './routes/bill-demo/audience/index'
import { Route as BillDemoArrayIndexRouteImport } from './routes/bill-demo/array/index'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const BillDemoStepperIndexRoute = BillDemoStepperIndexRouteImport.update({
  id: '/bill-demo/stepper/',
  path: '/bill-demo/stepper/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillDemoSimpleIndexRoute = BillDemoSimpleIndexRouteImport.update({
  id: '/bill-demo/simple/',
  path: '/bill-demo/simple/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillDemoDynamicIndexRoute = BillDemoDynamicIndexRouteImport.update({
  id: '/bill-demo/dynamic/',
  path: '/bill-demo/dynamic/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillDemoAudienceIndexRoute = BillDemoAudienceIndexRouteImport.update({
  id: '/bill-demo/audience/',
  path: '/bill-demo/audience/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillDemoArrayIndexRoute = BillDemoArrayIndexRouteImport.update({
  id: '/bill-demo/array/',
  path: '/bill-demo/array/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/bill-demo/array': typeof BillDemoArrayIndexRoute
  '/bill-demo/audience': typeof BillDemoAudienceIndexRoute
  '/bill-demo/dynamic': typeof BillDemoDynamicIndexRoute
  '/bill-demo/simple': typeof BillDemoSimpleIndexRoute
  '/bill-demo/stepper': typeof BillDemoStepperIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/bill-demo/array': typeof BillDemoArrayIndexRoute
  '/bill-demo/audience': typeof BillDemoAudienceIndexRoute
  '/bill-demo/dynamic': typeof BillDemoDynamicIndexRoute
  '/bill-demo/simple': typeof BillDemoSimpleIndexRoute
  '/bill-demo/stepper': typeof BillDemoStepperIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/bill-demo/array/': typeof BillDemoArrayIndexRoute
  '/bill-demo/audience/': typeof BillDemoAudienceIndexRoute
  '/bill-demo/dynamic/': typeof BillDemoDynamicIndexRoute
  '/bill-demo/simple/': typeof BillDemoSimpleIndexRoute
  '/bill-demo/stepper/': typeof BillDemoStepperIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/bill-demo/array'
    | '/bill-demo/audience'
    | '/bill-demo/dynamic'
    | '/bill-demo/simple'
    | '/bill-demo/stepper'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/bill-demo/array'
    | '/bill-demo/audience'
    | '/bill-demo/dynamic'
    | '/bill-demo/simple'
    | '/bill-demo/stepper'
  id:
    | '__root__'
    | '/'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/bill-demo/array/'
    | '/bill-demo/audience/'
    | '/bill-demo/dynamic/'
    | '/bill-demo/simple/'
    | '/bill-demo/stepper/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  BillDemoArrayIndexRoute: typeof BillDemoArrayIndexRoute
  BillDemoAudienceIndexRoute: typeof BillDemoAudienceIndexRoute
  BillDemoDynamicIndexRoute: typeof BillDemoDynamicIndexRoute
  BillDemoSimpleIndexRoute: typeof BillDemoSimpleIndexRoute
  BillDemoStepperIndexRoute: typeof BillDemoStepperIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bill-demo/stepper/': {
      id: '/bill-demo/stepper/'
      path: '/bill-demo/stepper'
      fullPath: '/bill-demo/stepper'
      preLoaderRoute: typeof BillDemoStepperIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bill-demo/simple/': {
      id: '/bill-demo/simple/'
      path: '/bill-demo/simple'
      fullPath: '/bill-demo/simple'
      preLoaderRoute: typeof BillDemoSimpleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bill-demo/dynamic/': {
      id: '/bill-demo/dynamic/'
      path: '/bill-demo/dynamic'
      fullPath: '/bill-demo/dynamic'
      preLoaderRoute: typeof BillDemoDynamicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bill-demo/audience/': {
      id: '/bill-demo/audience/'
      path: '/bill-demo/audience'
      fullPath: '/bill-demo/audience'
      preLoaderRoute: typeof BillDemoAudienceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bill-demo/array/': {
      id: '/bill-demo/array/'
      path: '/bill-demo/array'
      fullPath: '/bill-demo/array'
      preLoaderRoute: typeof BillDemoArrayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  BillDemoArrayIndexRoute: BillDemoArrayIndexRoute,
  BillDemoAudienceIndexRoute: BillDemoAudienceIndexRoute,
  BillDemoDynamicIndexRoute: BillDemoDynamicIndexRoute,
  BillDemoSimpleIndexRoute: BillDemoSimpleIndexRoute,
  BillDemoStepperIndexRoute: BillDemoStepperIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
